// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaBwnI32EE40fh_g0Yz8yTYJjn1v8lAgQ',
    appId: '1:546829217356:web:8c5a7aa8bb8af0834e4ee9',
    messagingSenderId: '546829217356',
    projectId: 'karyatoak',
    authDomain: 'karyatoak.firebaseapp.com',
    storageBucket: 'karyatoak.firebasestorage.app',
    measurementId: 'G-JLJKGPDR7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBxNsV-zABW7fL3LY3mq-0MjwnmccoY3g',
    appId: '1:546829217356:android:cc9bef3477d7bc4e4e4ee9',
    messagingSenderId: '546829217356',
    projectId: 'karyatoak',
    storageBucket: 'karyatoak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6i6pSGXNzzQBvHOTgo5vHU625rx3DHg0',
    appId: '1:546829217356:ios:56bb60f5482c596c4e4ee9',
    messagingSenderId: '546829217356',
    projectId: 'karyatoak',
    storageBucket: 'karyatoak.firebasestorage.app',
    iosClientId: '546829217356-sfml52pr73ca975o2stho3o356gvvvq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.persentasiKarya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6i6pSGXNzzQBvHOTgo5vHU625rx3DHg0',
    appId: '1:546829217356:ios:56bb60f5482c596c4e4ee9',
    messagingSenderId: '546829217356',
    projectId: 'karyatoak',
    storageBucket: 'karyatoak.firebasestorage.app',
    iosClientId: '546829217356-sfml52pr73ca975o2stho3o356gvvvq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.persentasiKarya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3pNKPgRLrXPmeEDBafXWvmGX0snyzOOE',
    appId: '1:546829217356:web:889aa87323f5dd234e4ee9',
    messagingSenderId: '546829217356',
    projectId: 'karyatoak',
    authDomain: 'karyatoak.firebaseapp.com',
    storageBucket: 'karyatoak.firebasestorage.app',
    measurementId: 'G-VE0KQEBS1S',
  );
}
